# Use the official Rust image.
FROM rust:1.72.0 as builder

# Create a new empty shell project
RUN USER=root cargo new --bin myapp
WORKDIR /myapp

# Copy our manifests and fetch only the dependencies.
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml
RUN cargo fetch

# Copy the source code.
COPY ./src ./src

# Build the release binary.
RUN cargo build --release

# Final base image
FROM debian:buster-slim

# Copy the binary from the builder stage.
COPY --from=builder /myapp/target/release/myapp /usr/local/bin/myapp

# Set the startup command to run the binary.
CMD ["myapp"]
